### ISSUE TITLE
Erro ao executar harvester

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_webservices#12]
2016-09-26 19:18:28,508 Processing data...
2016-09-26 19:19:34,348 Deleting entries...
S0365-05962005000500033:scl
Traceback (most recent call last):
  File "harvest_job.py", line 49, in <module>
    (add_update_article_entry, delete_article_entry)
  File "/var/www/pulsemob_webservices/pulsemob_webservices/harvest.py", line 176, in harvest
    delete_entries(curs, data_table_name, delete_entry)
  File "/var/www/pulsemob_webservices/pulsemob_webservices/harvest.py", line 91, in delete_entries
    delete_entry_method(row[0])
  File "harvest_job.py", line 15, in delete_article_entry
    solr_conn.delete(code=code)
  File "/home/gandalf/.virtualenvs/pulsemob_webservices/lib/python2.7/site-packages/solr/core.py", line 324, in wrapper
    content = function(self, _args, *_kw)
TypeError: delete() got an unexpected keyword argument 'code'

**Comment by fabiobatalha** [comment]
Tenho que comentar a rotina de remoção de registros para que a inclusão de novos registros termine sem interrupção.

**Comment by ghost** [comment]
Imagino que isso esteja ocorrendo porque a tabela article_data ainda está com dados da execução anterior. Limpa essa tabela e execute novamente.
