### ISSUE TITLE
Harvester deve ser resiliente.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_webservices#7]
Os metadados do SciELO não são normalizados, podem ocorrer inconsistências diversas que podem gerar erros como o do traceback abaixo.

```
Traceback (most recent call last):
  File "harvest_job.py", line 49, in <module>
    (add_update_article_entry, delete_article_entry)
  File "/var/www/pulsemob_webservices/pulsemob_webservices/harvest.py", line 180, in harvest
    add_update_entries(curs, temp_table, article_meta_uri, endpoint, add_update_entry, "I", indexed_date)
  File "/var/www/pulsemob_webservices/pulsemob_webservices/harvest.py", line 132, in add_update_entries
    add_update_entry_method(identifier, doc_ret, action, indexed_date)
  File "harvest_job.py", line 19, in add_update_article_entry
    args = solr_util.get_solr_args_from_article(document, indexed_date)
  File "/var/www/pulsemob_webservices/pulsemob_webservices/solr_util.py", line 78, in get_solr_args_from_article
    for item_category in article.journal.subject_areas:
TypeError: 'NoneType' object is not iterable
```

Esse erro acontece no momento de gerar a estrututura de dado para carga no Solr ou no Postgres.

O Harvester tem que espero o suficiente para tratar qualquer tipo de erro, jogando o traceback para logs sem paralizar o processamento.

**Comment by fabiobatalha** [comment]
Processamento continua com problemas
